import Info from "./components/Info/Info.js";
import TopSection from "./components/TopSection/TopSection.js";

export const metadata = {
  title: "About us",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <main>
      <TopSection/>
      <Info />
    </main>
  );
};

export default About;
