import Post from "@/app/components/Post/Post.js";

const fetchDetails = async (id) => {
  try {
    const res = await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`);
    if (!res.ok)
      throw new Error("Something went wrong!");

    const result = await res.json();

    return result;
  } catch (error) {
    console.log(error);
  }
};

export const generateMetadata = async ({ params, searchParams }) => {
  const res = await fetchDetails(params.postId);
  if(!res){
    return {
      title: "Post",
      description: "Generated by create next app",
    }
  }
  return {
    title: res.title,
    description: res.body,
  };
};

const PagePost = async ({ params: { postId } }) => {
  const data = await fetchDetails(postId);

  return (
    <main style={{ height: "100vh" }}>
      <Post data={data} />
    </main>
  );
};

export default PagePost;
